package pairingmvp

const indexHTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>EnvBank Pairing Lab</title>
<style nonce="__CSP_NONCE__">
:root{color-scheme:dark;--bg:#0b1020;--panel:#151d31;--line:#293551;--ink:#eef3ff;--muted:#9aa8c6;--accent:#7dd3fc;--good:#86efac;--warn:#fcd34d;--danger:#fca5a5}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#18243d,var(--bg) 48%);color:var(--ink);font:15px/1.5 system-ui,sans-serif}.shell{max-width:1160px;margin:auto;padding:34px 22px 60px}h1{font-size:28px;margin:0 0 6px}h2{font-size:18px;margin-top:0}.lede,.muted{color:var(--muted)}.badge{display:inline-block;padding:3px 9px;border:1px solid var(--line);border-radius:99px;color:var(--accent);font:12px ui-monospace,monospace}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:24px}.panel{background:rgba(21,29,49,.94);border:1px solid var(--line);border-radius:14px;padding:20px;min-width:0}.step{border-top:1px solid var(--line);padding-top:16px;margin-top:16px}.row{display:flex;gap:9px;align-items:center;flex-wrap:wrap}input,textarea,button{font:inherit;border-radius:8px}input,textarea{width:100%;background:#0d1426;color:var(--ink);border:1px solid #394766;padding:10px}textarea{min-height:102px;resize:vertical;font:12px/1.45 ui-monospace,monospace}button{background:#2577a5;color:white;border:0;padding:10px 14px;cursor:pointer}button.secondary{background:#34415d}button.danger{background:#8b3944}button:disabled{opacity:.42;cursor:not-allowed}.fingerprint{font:700 21px/1.3 ui-monospace,monospace;letter-spacing:.06em;color:var(--warn)}#qr{width:220px;height:220px;background:white;border-radius:8px;padding:8px;display:none}.status{margin-top:18px;padding:12px;border-radius:9px;background:#0d1426;color:var(--muted);white-space:pre-wrap}.success{color:var(--good)}.terminal{color:var(--danger)}@media(max-width:780px){.grid{grid-template-columns:1fr}}
</style></head><body><main class="shell"><span class="badge">DISPOSABLE DEVELOPER LAB</span><h1>Pair a new EnvBank device</h1><p class="lede">QR-first transfer with explicit approval. The QR locates a pending request; possession never grants vault access.</p>
<div class="grid"><section class="panel"><h2>New device</h2><div class="step"><label for="name">Synthetic device name</label><div class="row"><input id="name" value="Lab phone" maxlength="64"><button id="request">Create invitation</button></div></div><div class="step"><img id="qr" alt="Pairing QR code"><label for="payload">Copyable pairing payload</label><textarea id="payload" readonly spellcheck="false"></textarea><div class="row"><button id="copy" class="secondary">Copy payload</button><button id="cancel" class="danger">Cancel invitation</button></div></div><div class="step"><button id="accept">Refresh and accept envelope</button><p id="membership" class="muted">Waiting for approval.</p></div></section>
<section class="panel"><h2>Approved device</h2><div class="step"><label for="importPayload">Import scanned or pasted payload</label><textarea id="importPayload" spellcheck="false"></textarea><button id="import">Fetch pending invitation</button></div><div class="step"><p>Compare the complete fingerprint on both devices:</p><div id="fingerprint" class="fingerprint">—</div><label for="confirm">Enter all 16 hex characters</label><input id="confirm" maxlength="19" autocomplete="off" spellcheck="false"><div class="row"><button id="approve">Approve and wrap vault key</button><button id="reject" class="danger">Reject</button></div></div></section></div>
<div id="status" class="status">Loading…</div><p><button id="reset" class="secondary">Reset disposable lab</button></p></main>
<script nonce="__CSP_NONCE__">const csrf="__CSRF_TOKEN__";let state;
const $=id=>document.getElementById(id);async function api(path,body){const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body),credentials:'same-origin'});const data=await r.json();if(!r.ok)throw new Error(data.error||('HTTP '+r.status));return data}
function remaining(s){if(!s.expires_at||s.invitation_state!=='pending')return '—';return Math.max(0,Math.ceil((Date.parse(s.expires_at)-Date.now())/1000))+'s'}
function render(s){state=s;$('payload').value=s.pairing_payload||'';if(!$('importPayload').value&&s.pairing_payload)$('importPayload').value=s.pairing_payload;$('fingerprint').textContent=s.fingerprint||'—';$('qr').style.display=s.pairing_payload?'block':'none';if(s.pairing_payload)$('qr').src='/api/qr#'+Date.now();$('request').disabled=s.phase!=='idle';$('import').disabled=s.phase!=='requested';$('approve').disabled=s.phase!=='imported';$('reject').disabled=s.phase!=='imported';$('cancel').disabled=!['requested','imported'].includes(s.phase);$('accept').disabled=s.phase!=='approved';const terminal=['cancelled','rejected','expired','attempts_exhausted'].includes(s.phase);$('membership').textContent=s.same_vault_key?'Membership confirmed: the envelope unwrapped to the same vault key (key not displayed).':terminal?'Invitation ended: '+s.phase+'.':'Waiting for a valid approved envelope.';$('membership').className=s.same_vault_key?'success':terminal?'terminal':'muted';$('status').textContent='Lab phase: '+s.phase+'\nServer invitation state: '+(s.invitation_state||'—')+'\nAuthoritative expiry: '+(s.expires_at||'—')+'\nAdvisory countdown: '+remaining(s)+'\nAttempts remaining: '+(s.invitation_state?s.attempts_remaining:'—')+'\nService: '+s.server+'\nVault: '+s.vault_id}
async function act(path,body){try{render(await api(path,body))}catch(e){$('status').textContent='Stopped: '+e.message}}
$('request').onclick=()=>act('/api/request',{name:$('name').value});$('import').onclick=()=>act('/api/import',{payload:$('importPayload').value});$('approve').onclick=()=>act('/api/approve',{fingerprint:$('confirm').value});$('reject').onclick=()=>act('/api/reject',{});$('cancel').onclick=()=>act('/api/cancel',{});$('accept').onclick=()=>act('/api/accept',{});$('reset').onclick=()=>{ $('importPayload').value='';$('confirm').value='';act('/api/reset',{})};$('copy').onclick=()=>navigator.clipboard?navigator.clipboard.writeText($('payload').value):undefined;api('/api/state').then(render).catch(e=>$('status').textContent=e.message);setInterval(()=>{if(state)render(state)},1000);setInterval(()=>{if(state&&state.invitation_state==='pending')act('/api/refresh',{})},5000);
</script></body></html>`
